name: Deploy preview

on:
  pull_request:
    branches:
      - "main"
    types: [opened, synchronize]

jobs:
  deploy-preview:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./app
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - name: Deploy web
        id: web-deploy
        uses: amondnet/vercel-action@v25
        with:
          vercel-token: ${{ secrets.VERCEL_ACCESS_TOKEN }}
          github-comment: false
          vercel-org-id: nvCGfeFwl6TFmDBC02P3di0D
          vercel-args: "-A app/vercel.json"
          vercel-project-id: prj_LzMFljI4QanLq9Z5pp1zmhQX9zBQ
      - name: preview-url
        run: |
          echo ${{ steps.web-deploy.outputs.preview-url }}
