name: Deploy preview

on:
  pull_request:
    branches:
      - "main"
    types: [opened, synchronize]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./app
        id: vercel-action
        with:
          vercel-token: ${{ secrets.VERCEL_ACCESS_TOKEN }}
          github-comment: false
          vercel-org-id: nvCGfeFwl6TFmDBC02P3di0D
          vercel-args: "-A app/vercel.json"
          vercel-project-id: prj_LzMFljI4QanLq9Z5pp1zmhQX9zBQ
      - name: preview-url
        run: |
          echo ${{ steps.vercel-action.outputs.preview-url }}
